// 한글 은행명을 영문 파일명으로 매핑
export const bankNameMap = {
    경남은행: 'gyeongnam',
    광주은행: 'gwangju',
    부산은행: 'busan',
    신한은행: 'shinhan',
    신협은행: 'shinhyup',
    우리은행: 'woori',
    우리투자은행: 'woori',
    우정사업본부: 'epost',
    전북은행: 'jeonbuk',
    제주은행: 'jeju',
    카카오뱅크: 'kakao',
    케이뱅크: 'kbank',
    토스뱅크: 'toss',
    하나은행: 'hana',
    IBK기업은행: 'ibk',
    아이엠뱅크: 'imbank',
    KB국민은행: 'kb',
    KDB산업은행: 'kdb',
    NH농협은행: 'nh',
    SC제일은행: 'sc',
    SH수협은행: 'sh',
};
