// 한글 은행명을 영문 파일명으로 매핑
export const bankNameMap = {
    경남: 'gyeongnam',
    광주: 'gwangju',
    부산: 'busan',
    신한: 'shinhan',
    신협: 'shinhyup',
    우리: 'woori',
    우리투자: 'woori',
    우정사업본부: 'epost',
    전북: 'jeonbuk',
    제주: 'jeju',
    카카오뱅크: 'kakao',
    케이뱅크: 'kbank',
    토스뱅크: 'toss',
    하나: 'hana',
    IBK기업: 'ibk',
    iM뱅크: 'imbank',
    KB국민: 'kb',
    KDB산업: 'kdb',
    NH농협: 'nh',
    SC제일: 'sc',
    SH수협: 'sh',
};
