export const bankUriMap = {
  한국스탠다드차타드은행: 'https://www.standardchartered.co.kr/',
  '주식회사 케이뱅크': 'https://www.kbanknow.com/',
  국민은행: 'https://obank.kbstar.com/',
  부산은행: 'https://www.busanbank.co.kr/',
  중소기업은행: 'https://www.ibk.co.kr/',
  한국산업은행: 'https://www.kdb.co.kr/',
  농협은행주식회사: 'https://www.nonghyup.com/',
  전북은행: 'https://www.jbbank.co.kr/',
  '주식회사 카카오뱅크': 'https://www.kakaobank.com/',
  '토스뱅크 주식회사': 'https://www.tossbank.com/',
  수협은행: 'https://www.suhyup-bank.com/',
  제주은행: 'https://www.e-jejubank.com/',
  아이엠뱅크: 'https://www.imbank.co.kr/dgb_ebz_main.jsp',
  신한은행: 'https://bank.shinhan.com/',
  경남은행: 'https://www.knbank.co.kr/',
  '주식회사 하나은행': 'https://www.kebhana.com/',
  광주은행: 'https://www.kjbank.com/',
  우리은행: 'https://wooribank.com/',
};
