export const bankNameMap = {
  경남은행: 'gyeongnam',
  광주은행: 'gwangju',
  부산은행: 'busan',
  신한은행: 'shinhan',
  신협은행: 'shinhyup',
  우리은행: 'woori',
  우리투자은행: 'woori',
  우정사업본부: 'epost',
  전북은행: 'jeonbuk',
  제주은행: 'jeju',
  '주식회사 카카오뱅크': 'kakao',
  '주식회사 케이뱅크': 'kbank',
  '토스뱅크 주식회사': 'toss',
  '주식회사 하나은행': 'hana',
  중소기업은행: 'ibk',
  아이엠뱅크: 'imbank',
  국민은행: 'kb',
  KDB산업은행: 'kdb',
  농협은행주식회사: 'nh',
  한국스탠다드차타드은행: 'sc',
  수협은행: 'sh',
};